---
version: "2"
plugins:
  duplication:
    enabled: false
  eslint:
    enabled: true
    channel: "eslint-6"
    checks:
      import/no-unresolved:
        enabled: false
      import/extensions:
        enabled: false
      implicit-arrow-linebreak:
        enabled: false
      no-use-before-define:
        enabled: false
      object-curly-newline:
        enabled: false
      no-unsanitized/method:
        enabled: false
      no-unsanitized/property:
        enabled: false
      prefer-destructuring:
        enabled: false
    config:
      extensions:
      - .js
      - .jsx
exclude_patterns:
  - "node_modules/"
  - "migrations/"
  - "test/"
  - "scripts/"
  - "coverage/"
  - "migrate.js"