version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile-app
      context: .
    command: ["scripts/wait-for-it.sh", "db:5432", "--", "yarn", "watch"]
    volumes:
      - .:/app:delegated
      - node-modules:/app/node_modules/
      - yarn-cache:/app/.yarn-cache/
    ports:
      - "1337:1337" # for the app itself
      - "8888:8888" # for viewing analyze-webpack
      - "8080:8080" # for serving test coverage html
    depends_on:
      - db
  db:
    build:
      dockerfile: Dockerfile-db
      context: .
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # expose db on host at port 5433
    environment:
      POSTGRES_DB: federalist
      POSTGRES_TEST_DB: federalist-test
volumes:
  db-data:
  yarn-cache:
  node-modules:

