version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile-app
      context: .
    command: ["scripts/wait-for-it.sh", "db:5432", "--", "yarn", "watch"]
    volumes:
      - .:/app
    ports:
      - "1337:1337" # for the app itself
      - "8888:8888" # for viewing analyze-webpack
      - "8080:8080" # for serving test coverage html
    depends_on:
      - db
    environment:
      JWT_SECRET: 'shhHhh...'
      USER_AUDITOR: federalist
  admin-client:
    build:
      context: ./admin-client
    working_dir: /app
    volumes:
      - ./admin-client:/app
    ports:
      - "3000:3000"
      - "10000:10000"
    depends_on:
      - db
    command: ["yarn", "dev"]
  db:
    build:
      dockerfile: Dockerfile-db
      context: .
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # expose db on host at port 5433
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: federalist
      POSTGRES_TEST_DB: federalist-test
volumes:
  db-data:
