name: federalistapp-staging
memory: 256MB
instances: 2
env: staging
env_postfix: -staging
log_level: verbose
feature_admin_auth: 'true'
feature_proxy_edge_links: 'true'
feature_proxy_edge_dynamo: 'true'
auth_idp: sso